import type { Command } from "commander";
import type { ConfigStore } from "../config/store.js";
import { refreshExternalTools } from "../tools/external-cli.js";
import type { ToolRegistry } from "../tools/registry.js";

export type CompletionShell = "bash" | "zsh" | "fish" | "powershell";

const shells: CompletionShell[] = ["bash", "zsh", "fish", "powershell"];

function visibleCommands(command: Command): Command[] {
  return command.commands.filter((candidate) => candidate.name() !== "__complete" && !(candidate as Command & { _hidden?: boolean })._hidden);
}

function optionValues(command: Command): string[] {
  return command.options
    .filter((option) => !option.hidden)
    .flatMap((option) => [option.short, option.long].filter((value): value is string => Boolean(value)));
}

function commandPath(root: Command, tokens: string[]): { command: Command; path: string[] } {
  let command = root;
  const path: string[] = [];
  for (const token of tokens) {
    const child = visibleCommands(command).find((candidate) => candidate.name() === token);
    if (!child) break;
    command = child;
    path.push(token);
  }
  return { command, path };
}

async function cachedExternalToolNames(store: ConfigStore, registry: ToolRegistry): Promise<string[]> {
  try {
    // Loading cached reviews through the regular discovery path keeps this
    // completion query offline: no provider is supplied, so no help probe or
    // model request can occur.
    const config = await store.loadConfig();
    await refreshExternalTools({
      registry,
      config,
      stateDir: store.paths.stateDir,
      signal: AbortSignal.timeout(1500)
    });
  } catch {
    // Completion must remain useful when a registered PATH command is unavailable.
  }
  return registry.entries().map((tool) => tool.definition.function.name);
}

async function profileNames(store: ConfigStore): Promise<string[]> {
  try {
    return Object.keys((await store.loadConfig()).profiles).sort();
  } catch {
    return [];
  }
}

async function registeredExternalCommands(store: ConfigStore): Promise<string[]> {
  try {
    return (await store.loadConfig()).externalCli.commands.slice().sort();
  } catch {
    return [];
  }
}

async function candidates(
  root: Command,
  words: string[],
  store: ConfigStore | undefined,
  registry: ToolRegistry | undefined
): Promise<string[]> {
  const input = words[0] && !inputLooksLikeCommand(words[0]) ? words.slice() : words.slice(1);
  const prefix = input.pop() ?? "";
  const resolved = commandPath(root, input.filter((token) => !token.startsWith("-")));
  const previous = input.at(-1);
  let values: string[];

  if (previous === "--profile" || previous === "-p" || prefix.startsWith("--profile=")) {
    values = store ? await profileNames(store) : [];
    if (prefix.startsWith("--profile=")) {
      const profilePrefix = prefix.slice("--profile=".length);
      return values
        .map((value) => `--profile=${value}`)
        .filter((value) => value.startsWith(`--profile=${profilePrefix}`))
        .sort();
    }
  } else if (resolved.path.at(-2) === "tools" && resolved.path.at(-1) === "show" && store && registry) {
    values = await cachedExternalToolNames(store, registry);
  } else if (resolved.path.at(-2) === "tools" && resolved.path.at(-1) === "unregister" && store) {
    values = await registeredExternalCommands(store);
  } else {
    values = [
      ...visibleCommands(resolved.command).map((command) => command.name()),
      ...optionValues(resolved.command),
      ...optionValues(root),
      "-h",
      "--help"
    ];
  }
  return [...new Set(values)].filter((value) => value.startsWith(prefix)).sort();
}

function inputLooksLikeCommand(value: string): boolean {
  return value === "cj" || value.endsWith("/cj") || value.endsWith("\\cj") || value.endsWith("cj.js");
}

function bashScript(): string {
  return `# bash completion for cj (generated by cj completion bash)
_cj_completion() {
  local cj_command="\${CJ_COMMAND:-cj}"
  local -a replies
  mapfile -t replies < <("$cj_command" __complete bash -- "\${COMP_WORDS[@]}" 2>/dev/null)
  COMPREPLY=("\${replies[@]}")
}
complete -F _cj_completion cj
`;
}

function zshScript(): string {
  return `#compdef cj
# zsh completion for cj (generated by cj completion zsh)
_cj_completion() {
  local -a replies
  replies=("\${(@f)$(\${CJ_COMMAND:-cj} __complete zsh -- "\${words[@]}" 2>/dev/null)}")
  compadd -- "\${replies[@]}"
}
compdef _cj_completion cj
`;
}

function fishScript(): string {
  return `# fish completion for cj (generated by cj completion fish)
function __cj_completion
  set -l cj_command cj
  if set -q CJ_COMMAND
    set cj_command $CJ_COMMAND
  end
  set -l tokens (commandline -opc)
  set -a tokens (commandline -ct)
  $cj_command __complete fish -- $tokens 2>/dev/null
end
complete -c cj -f -a '(__cj_completion)'
`;
}

function powershellScript(): string {
  return `# PowerShell completion for cj (generated by cj completion powershell)
Register-ArgumentCompleter -Native -CommandName cj -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $cjCommand = if ($env:CJ_COMMAND) { $env:CJ_COMMAND } else { 'cj' }
  $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
  & $cjCommand __complete powershell -- @tokens 2>$null |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
}

export function renderCompletion(shell: CompletionShell): string {
  if (shell === "bash") return bashScript();
  if (shell === "zsh") return zshScript();
  if (shell === "fish") return fishScript();
  return powershellScript();
}

export function addCompletionCommand(program: Command, store: ConfigStore, registry: ToolRegistry): void {
  program
    .command("completion")
    .description("Generate shell completion scripts")
    .argument("<shell>", "bash, zsh, fish or powershell")
    .addHelpText("after", "\nExample: eval \"$(cj completion bash)\"\n")
    .action((shell: string) => {
      if (!shells.includes(shell as CompletionShell)) {
        throw new Error(`Unsupported shell: ${shell}. Choose ${shells.join(", ")}`);
      }
      process.stdout.write(renderCompletion(shell as CompletionShell));
    });

  const internal = program
    .command("__complete", { hidden: true })
    .description("internal completion query")
    .allowUnknownOption()
    .allowExcessArguments(true)
    .argument("<shell>")
    .argument("[words...]" );
  internal.action(async (shell: string, words: string[]) => {
    if (!shells.includes(shell as CompletionShell)) return;
    const values = await candidates(program, words ?? [], store, registry);
    process.stdout.write(`${values.join("\n")}${values.length ? "\n" : ""}`);
  });
}
