# bash completion for cj (generated by cj completion bash)
_cj_completion() {
  local cj_command="${CJ_COMMAND:-cj}"
  local -a replies
  mapfile -t replies < <("$cj_command" __complete bash -- "${COMP_WORDS[@]}" 2>/dev/null)
  COMPREPLY=("${replies[@]}")
}
complete -F _cj_completion cj
