complete -c cj -l json -d 'Emit JSON Lines events'
complete -c cj -l verbose -d 'Show detailed Tool results'
complete -c cj -l dry-run -d 'Preview Tool actions without executing them'
complete -c cj -l task-events -d 'Emit task lifecycle events'
complete -c cj -n '__fish_use_subcommand' -a chat -d 'Start an interactive chat session'
complete -c cj -n '__fish_use_subcommand' -a config -d 'Manage configuration and profiles'
complete -c cj -n '__fish_use_subcommand' -a doctor -d 'Validate configuration'
complete -c cj -n '__fish_use_subcommand' -a history -d 'View redacted audit history'
complete -c cj -n '__fish_use_subcommand' -a memory -d 'Manage local memory'
complete -c cj -n '__fish_use_subcommand' -a tools -d 'Inspect Tools'
complete -c cj -n '__fish_use_subcommand' -a version -d 'Show version diagnostics'
