# fish completion for cj (generated by cj completion fish)
function __cj_completion
  set -l cj_command cj
  if set -q CJ_COMMAND
    set cj_command $CJ_COMMAND
  end
  set -l tokens (commandline -opc)
  set -a tokens (commandline -ct)
  $cj_command __complete fish -- $tokens 2>/dev/null
end
complete -c cj -f -a '(__cj_completion)'
