# PowerShell completion for cj (generated by cj completion powershell)
Register-ArgumentCompleter -Native -CommandName cj -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $cjCommand = if ($env:CJ_COMMAND) { $env:CJ_COMMAND } else { 'cj' }
  $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
  & $cjCommand __complete powershell -- @tokens 2>$null |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
