#compdef cj
# zsh completion for cj (generated by cj completion zsh)
_cj_completion() {
  local -a replies
  replies=("${(@f)$(${CJ_COMMAND:-cj} __complete zsh -- "${words[@]}" 2>/dev/null)}")
  compadd -- "${replies[@]}"
}
compdef _cj_completion cj
